### ISSUE TITLE
Include this in CAS?

### ISSUE THREAD

**Issue by mmoayyed** [izerui/cas-ticket-redis#1]
Hello,
1. Would it be possible for you to submit a PR to the CAS project, including this registry?
2. If not, would it be OK if we borrowed this registry from this repo and included it in CAS?

Thanks

**Comment by izerui** [comment]
yes，it is possible ！any way

**Comment by izerui** [comment]
@mmoayyed 👍  
I created a new project，It might be helpful to you ，please check it ! 
https://github.com/izerui/cas-server-integration-redis

**Comment by mmoayyed** [comment]
Great. Could you convert this one to use CAS 5 instead?

**Comment by izerui** [comment]
Ok, I will try to submit a pull request to cas5!  :)
