### ISSUE TITLE
对于cas集群部署

### ISSUE THREAD

**Issue by LiJohnson** [izerui/cas-ticket-redis#2]
测试版本**cas4.2.3**
1. cas本身没有将信息存session的，所以session可以不用作共享
1. 只要将ticket共享就可以了
1. 要配 gtc key `tgc.encryption.key` 和`tgc.signing.key`

**Comment by izerui** [comment]
是的，README上描述有误， 只是将ticket 做了redis统一存取策略

**Comment by izerui** [comment]
多谢指正！enjoy!!

**Comment by soldierTOT** [comment]
测试版本cas4.2.7
       按照配置在两个tomcat上部署两个cas后(已做session共享)，ticket已保存到redis中，但无法实现ticket共享，第一个tomcat上的cas登录成功后，第二个tomcat在同浏览器登录时仍需登录。请问是否cas.properties中需要默写配置的修改？
